// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fs_var_num
List fs_var_num(NumericMatrix Z, Nullable<NumericVector> mult, Nullable<IntegerVector> zrow, IntegerVector g, int G, IntegerVector strat_ptr, IntegerVector psu_ptr, IntegerVector rows, NumericVector fpc_f, int lonely, bool full, int nthreads);
RcppExport SEXP _rapidsvy_fs_var_num(SEXP ZSEXP, SEXP multSEXP, SEXP zrowSEXP, SEXP gSEXP, SEXP GSEXP, SEXP strat_ptrSEXP, SEXP psu_ptrSEXP, SEXP rowsSEXP, SEXP fpc_fSEXP, SEXP lonelySEXP, SEXP fullSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type mult(multSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type zrow(zrowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strat_ptr(strat_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type psu_ptr(psu_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fpc_f(fpc_fSEXP);
    Rcpp::traits::input_parameter< int >::type lonely(lonelySEXP);
    Rcpp::traits::input_parameter< bool >::type full(fullSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fs_var_num(Z, mult, zrow, g, G, strat_ptr, psu_ptr, rows, fpc_f, lonely, full, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fs_var_cat
List fs_var_cat(IntegerVector y, NumericVector w, IntegerVector g, int G, int K, NumericMatrix p, NumericVector Wg, IntegerVector strat_ptr, IntegerVector psu_ptr, IntegerVector rows, NumericVector fpc_f, int lonely, bool full, int nthreads);
RcppExport SEXP _rapidsvy_fs_var_cat(SEXP ySEXP, SEXP wSEXP, SEXP gSEXP, SEXP GSEXP, SEXP KSEXP, SEXP pSEXP, SEXP WgSEXP, SEXP strat_ptrSEXP, SEXP psu_ptrSEXP, SEXP rowsSEXP, SEXP fpc_fSEXP, SEXP lonelySEXP, SEXP fullSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wg(WgSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strat_ptr(strat_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type psu_ptr(psu_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fpc_f(fpc_fSEXP);
    Rcpp::traits::input_parameter< int >::type lonely(lonelySEXP);
    Rcpp::traits::input_parameter< bool >::type full(fullSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fs_var_cat(y, w, g, G, K, p, Wg, strat_ptr, psu_ptr, rows, fpc_f, lonely, full, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fs_grp_sum
NumericMatrix fs_grp_sum(NumericMatrix X, IntegerVector g, int G);
RcppExport SEXP _rapidsvy_fs_grp_sum(SEXP XSEXP, SEXP gSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(fs_grp_sum(X, g, G));
    return rcpp_result_gen;
END_RCPP
}
// fs_wquantile
NumericMatrix fs_wquantile(NumericVector x, NumericVector w, IntegerVector ptr, NumericMatrix P);
RcppExport SEXP _rapidsvy_fs_wquantile(SEXP xSEXP, SEXP wSEXP, SEXP ptrSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(fs_wquantile(x, w, ptr, P));
    return rcpp_result_gen;
END_RCPP
}
// fs_xtwx
List fs_xtwx(NumericMatrix X, NumericVector w, NumericVector z, int nthreads);
RcppExport SEXP _rapidsvy_fs_xtwx(SEXP XSEXP, SEXP wSEXP, SEXP zSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fs_xtwx(X, w, z, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rapidsvy_fs_var_num", (DL_FUNC) &_rapidsvy_fs_var_num, 12},
    {"_rapidsvy_fs_var_cat", (DL_FUNC) &_rapidsvy_fs_var_cat, 14},
    {"_rapidsvy_fs_grp_sum", (DL_FUNC) &_rapidsvy_fs_grp_sum, 3},
    {"_rapidsvy_fs_wquantile", (DL_FUNC) &_rapidsvy_fs_wquantile, 4},
    {"_rapidsvy_fs_xtwx", (DL_FUNC) &_rapidsvy_fs_xtwx, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rapidsvy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
