# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fs_var_num <- function(Z, mult, zrow, g, G, strat_ptr, psu_ptr, rows, fpc_f, lonely, full, nthreads) {
    .Call(`_rapidsvy_fs_var_num`, Z, mult, zrow, g, G, strat_ptr, psu_ptr, rows, fpc_f, lonely, full, nthreads)
}

fs_var_cat <- function(y, w, g, G, K, p, Wg, strat_ptr, psu_ptr, rows, fpc_f, lonely, full, nthreads) {
    .Call(`_rapidsvy_fs_var_cat`, y, w, g, G, K, p, Wg, strat_ptr, psu_ptr, rows, fpc_f, lonely, full, nthreads)
}

fs_grp_sum <- function(X, g, G) {
    .Call(`_rapidsvy_fs_grp_sum`, X, g, G)
}

fs_wquantile <- function(x, w, ptr, P) {
    .Call(`_rapidsvy_fs_wquantile`, x, w, ptr, P)
}

fs_xtwx <- function(X, w, z, nthreads) {
    .Call(`_rapidsvy_fs_xtwx`, X, w, z, nthreads)
}

